"""empty message

Revision ID: 030a21c65e7b
Revises: 705f2072def7
Create Date: 2025-07-11 20:16:53.372536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030a21c65e7b'
down_revision = '705f2072def7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
