"""empty message

Revision ID: 106f2ad97589
Revises: 9a57b78f1c02
Create Date: 2025-07-17 16:19:17.038662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106f2ad97589'
down_revision = '9a57b78f1c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postularse', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('project_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_collaborators', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('postularse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False))

    # ### end Alembic commands ###
