"""empty message

Revision ID: 933caabfdca9
Revises: 111623aa30b4
Create Date: 2025-07-07 11:30:19.795118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933caabfdca9'
down_revision = '111623aa30b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stackblitz_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('stackblitz_url')

    # ### end Alembic commands ###
