"""empty message

Revision ID: 9a57b78f1c02
Revises: 030a21c65e7b
Create Date: 2025-07-15 17:38:39.223656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a57b78f1c02'
down_revision = '030a21c65e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postularse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postularse', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
