"""empty message

Revision ID: a1544ec76c1d
Revises: b85bff42a932
Create Date: 2025-07-06 17:51:55.552548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1544ec76c1d'
down_revision = 'b85bff42a932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('username')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('username')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
