"""empty message

Revision ID: d525f52b7c64
Revises: 23d5ae3b93d8
Create Date: 2025-07-07 12:32:15.829322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd525f52b7c64'
down_revision = '23d5ae3b93d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_files', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('code_files')

    # ### end Alembic commands ###
